# -*- coding: utf-8 -*-
"""modern_methods.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c7EOHoz8HvpmhJIVOvl1JhS5KvX3ceR9
"""

# ==========================================
# 檔名: modern_methods.py
# ==========================================

# 1. 安裝與匯入必要套件
try:
    import google.generativeai as genai
    import pandas as pd
    import numpy as np
    import pkg_resources
except ImportError:
    print("正在安裝 Part B 必要套件...")
    !pip install -q google-generativeai pandas numpy
    import google.generativeai as genai
    import pandas as pd
    import numpy as np
    import pkg_resources

from google.colab import userdata
import sys

# 2. 顯示套件版本
print("=== Part B 環境檢查 ===")
print(f"Python version: {sys.version.split()[0]}")
print(f"google-generativeai version: {pkg_resources.get_distribution('google-generativeai').version}")
print(f"pandas version: {pd.__version__}")
print(f"numpy version: {np.__version__}")
print("=======================\n")

# 3. 定義共用資料 (獨立存在於此檔案)
documents = [
    "人工智慧正在改變世界,機器學習是其核心技術",
    "深度學習推動了人工智慧的發展,特別是在圖像識別領域",
    "今天天氣很好,適合出去運動",
    "機器學習和深度學習都是人工智慧的重要分支",
    "運動有益健康,每天都應該保持運動習慣"
]

test_texts = [
    "這家餐廳的牛肉麵真的太好吃了,湯頭濃郁,麵條Q彈,下次一定再來!",
    "最新的AI技術突破讓人驚艷,深度學習模型的表現越來越好",
    "這部電影劇情空洞,演技糟糕,完全是浪費時間",
    "每天慢跑5公里,配合適當的重訓,體能進步很多"
]

long_text_example = """
人工智慧（Artificial Intelligence, AI）是電腦科學的一個分支，它試圖了解智能的實質，並生產出一種新的能以人類智能相似的方式做出反應的智能機器。
人工智慧的研究領域主要包括機器人、語言識別、圖像識別、自然語言處理和專家系統等。
自從人工智慧誕生以來，理論和技術日益成熟，應用領域也不斷擴大。
可以設想，未來人工智慧帶來的科技產品，將會是人類智慧的「容器」。
深度學習是機器學習中一種基於對數據進行表徵學習的演算法。
深度學習的好處是用非監督式或半監督式的特徵學習和分層特徵提取高效算法來替代手工獲取特徵。
"""

# 4. API 設定 (應放置在 b-1 之前，作為 Part B 的初始化)
print("=== Part B: 現代 AI (Gemini) 實作 ===")
try:
    api_key = userdata.get('AI')
    genai.configure(api_key=api_key)
    # 初始化模型
    model_gen = genai.GenerativeModel('gemini-2.5-flash-lite')
    print("\n✅ [B-1 前置] API Key 設定成功")
except Exception as e:
    print(f"\n❌ [B-1 前置] API Key 設定失敗: {e}")
    print("請確認 Colab 密鑰 (Secrets) 中已包含名稱為 'AI' 的金鑰")

# --- [B-1] GenAI 文本相似度 (Embeddings) ---
print("\n--- [B-1] GenAI 文本相似度 ---")
def get_embedding(text):
    try: return genai.embed_content(model="models/text-embedding-004", content=text)['embedding']
    except: return []

def manual_cosine(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)) if v1 and v2 else 0.0

v1, v2 = get_embedding(documents[0]), get_embedding(documents[1])
score_b1 = manual_cosine(v1, v2) * 100
print(f"GenAI 相似度 (Doc1 vs Doc2): {score_b1:.2f} / 100")

# --- [B-2] GenAI 文本分類 (含 CSV 生成) ---
print("\n--- [B-2] GenAI 文本分類 ---")
classification_results = []

for text in test_texts:
    prompt = f"""
    你是一個文本分類專家。請分析以下文本的「情感」、「主題」與「信心分數」。
    限制條件：
    1. 情感標籤：[正面, 負面, 中性]
    2. 主題標籤：[科技, 運動, 美食, 娛樂]
    3. 信心分數：0.00-1.00
    4. 請僅回傳以下格式字串，不要有其他文字：
       情感: [X] | 主題: [X] | 信心分數: [0.XX]

    文本: "{text}"
    """
    try:
        if 'model_gen' in globals():
            response = model_gen.generate_content(prompt).text.strip()
            print(f"文本: {text[:10]}... -> {response}")

            # 解析回傳結果以存入 CSV
            parts = [p.split(":")[1].strip() for p in response.split("|")]
            classification_results.append({
                "Text": text,
                "Sentiment": parts[0],
                "Topic": parts[1],
                "Confidence": parts[2]
            })
        else:
            print("模型未初始化，無法執行分類")
    except Exception as e:
        print(f"Error processing: {e}")

# 生成 classification_result.csv
df_cls = pd.DataFrame(classification_results)
df_cls.to_csv("classification_result.csv", index=False, encoding='utf-8-sig')
print("✅ 已生成 'classification_result.csv'")

# --- [B-3] GenAI 自動摘要 ---
print("\n--- [B-3] GenAI 自動摘要 ---")
prompt_sum = f"請用生成式摘要技術改寫以下文本，約50-80字，需含AI定義與深度學習重點:\n{long_text_example}"
try:
    if 'model_gen' in globals():
        print(model_gen.generate_content(prompt_sum).text.strip())
except: pass